-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 12:05:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BuenaVid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BuenaVid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BuenaVid` CHARACTER SET utf8mb4 ;
USE `BuenaVid` ;

-- -----------------------------------------------------
-- Table `BuenaVid`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `cellphone` VARCHAR(20) NULL,
  `date` DATE NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  ,
  INDEX `fk_users_roles1_idx` (`rol_id` ASC)  ,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `BuenaVid`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`wineries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`wineries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`origins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`origins` (
  `id` INT NOT NULL AUTO_INCREMENT, 
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `price` DECIMAL(9) NOT NULL,
  `discount` DECIMAL(2) NOT NULL,
  `recomended` TINYINT NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `winery_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `origin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `origin_id`),
  INDEX `fk_products_wineries1_idx` (`winery_id` ASC)  ,
  INDEX `fk_products_categories1_idx` (`category_id` ASC)  ,
  INDEX `fk_products_origins1_idx` (`origin_id` ASC)  ,
  CONSTRAINT `fk_products_wineries1`
    FOREIGN KEY (`winery_id`)
    REFERENCES `BuenaVid`.`wineries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `BuenaVid`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_origins1`
    FOREIGN KEY (`origin_id`)
    REFERENCES `BuenaVid`.`origins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `importe` DECIMAL(2) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_sales_users1_idx` (`users_id` ASC)  ,
  CONSTRAINT `fk_sales_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `BuenaVid`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`products_has_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`products_has_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `products_id` INT NOT NULL,
  `sales_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  INDEX `fk_products_has_sales_sales1_idx` (`sales_id` ASC)  ,
  INDEX `fk_products_has_sales_products1_idx` (`products_id` ASC)  ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_has_sales_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `BuenaVid`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_sales_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `BuenaVid`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`Payment_Methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`Payment_Methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuenaVid`.`Payment_Methods_has_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuenaVid`.`Payment_Methods_has_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Payment_Methods_id` INT NOT NULL,
  `sales_id` INT NOT NULL,
  INDEX `fk_Payment_Methods_has_sales_sales1_idx` (`sales_id` ASC)  ,
  INDEX `fk_Payment_Methods_has_sales_Payment_Methods1_idx` (`Payment_Methods_id` ASC)  ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Payment_Methods_has_sales_Payment_Methods1`
    FOREIGN KEY (`Payment_Methods_id`)
    REFERENCES `BuenaVid`.`Payment_Methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Methods_has_sales_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `BuenaVid`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
